---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nikitayatsko/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/practical_course?currentSchema=order_service"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -Xmx512m -Xms256m"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name : SPRING_EXTERNAL_KAFKA_SERVER
              value: "my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"
