CREATE SCHEMA IF NOT EXISTS order_service;
CREATE SCHEMA IF NOT EXISTS user_service;

CREATE TABLE IF NOT EXISTS user_service.users (
    id INT PRIMARY KEY
);

CREATE TABLE order_service.orders(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id INT REFERENCES user_service.users(id) ON DELETE SET NULL,
                       status VARCHAR(25) NOT NULL,
                       total_price NUMERIC(10, 2) NOT NULL,
                       deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_service.items(
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(50) NOT NULL UNIQUE,
                      price NUMERIC(10, 2) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_service.order_items(
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id INT REFERENCES order_service.orders(id) ON DELETE CASCADE NOT NULL,
                            item_id INT REFERENCES order_service.items(id) ON DELETE RESTRICT NOT NULL,
                            quantity INT NOT NULL,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);