--liquibase formatted sql

--changeset order_service:1
CREATE TABLE orders(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id INT REFERENCES user_service.users(id) ON DELETE SET NULL,
                       status VARCHAR(25) NOT NULL,
                       total_price NUMERIC(10, 2) NOT NULL CHECK ( total_price > 0 ),
                       deleted BOOLEAN NOT NULL DEFAULT FALSE,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_orders_user_id ON orders(user_id);

--changeset order_service:2
CREATE TABLE items(
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(50) NOT NULL UNIQUE,
                      price NUMERIC(10, 2) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--changeset order_service:3
CREATE TABLE order_items(
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id INT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
                            item_id INT REFERENCES items(id) ON DELETE RESTRICT NOT NULL,
                            quantity INT NOT NULL CHECK ( quantity > 0 ),
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_item_id ON order_items(item_id);
