--liquibase formatted sql

--changeset order_service:1
CREATE TABLE order_service.orders(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES user_service.users(user_id) ON DELETE SET NULL,
    status VARCHAR(25) NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_orders_user_id ON order_service.orders(user_id);

--changeset order_service:2
CREATE TABLE order_service.items(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--changeset order_service:3
CREATE TABLE order_service.order_items(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT REFERENCES order_service.orders(id) ON DELETE CASCADE NOT NULL,
    item_id INT REFERENCES order_service.items(id) ON DELETE RESTRICT NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_items_order_id ON order_service.order_items(order_id);
CREATE INDEX idx_order_items_item_id ON order_service.order_items(item_id);
